name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 📦
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies 📦
      run: dotnet restore

    - name: Build 🏗
      run: dotnet build --configuration Release --no-restore

    - name: Test 🧪
      run: dotnet test --configuration Release --no-build